CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ALLERGY (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RECIPE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    KCAL INT CHECK (KCAL >= 0),
    PROTEIN INT CHECK (PROTEIN >= 0),
    CARBS INT CHECK (CARBS >= 0),
    FATS INT CHECK (FATS >= 0),
    INGREDIENTS VARCHAR(1000),
    PRICE DECIMAL(8,2) NOT NULL CHECK (PRICE >= 0),
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE SET NULL
    );

CREATE TABLE IF NOT EXISTS RECIPE_ALLERGY (
RECIPE_ID INT NOT NULL,
ALLERGY_ID INT NOT NULL,
PRIMARY KEY (RECIPE_ID, ALLERGY_ID),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ALLERGY_ID) REFERENCES ALLERGY(ID) ON DELETE CASCADE
    );

-- Prepopulate ALLERGY table safely
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('GLUTEN');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('LACTOSE');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('NUTS');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('SEAFOOD');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('EGGS');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('SOY');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('SESAME');
MERGE INTO ALLERGY (TYPE) KEY(TYPE) VALUES ('MUSTARD');

MERGE INTO CATEGORY (NAME) KEY(NAME) VALUES ('Meat');
MERGE INTO CATEGORY (NAME) KEY(NAME) VALUES ('Vegetarian');
MERGE INTO CATEGORY (NAME) KEY(NAME) VALUES ('Dessert');
MERGE INTO CATEGORY (NAME) KEY(NAME) VALUES ('Seafood');
MERGE INTO CATEGORY (NAME) KEY(NAME) VALUES ('Pasta');

-- Prepopulate RECIPE table
INSERT INTO RECIPE(NAME, KCAL, PROTEIN, CARBS, FATS, INGREDIENTS, PRICE)
VALUES
    ('Tuna Pasta', 600, 30, 50, 15, 'pasta, tuna, olive oil, garlic, parsley', 4.99),
    ('Chicken Stir Fry', 550, 35, 40, 10, 'chicken, soy sauce, vegetables, rice', 5.49),
    ('Student Burrito', 750, 25, 60, 20, 'tortilla, beans, rice, cheese, salsa', 3.99),
    ('Katsu Chicken', 1000, 70, 90, 20, 'rice, tonkatsu sauce, fried chicken', 9.80);
