CREATE TABLE IF NOT EXISTS RECIPE (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100) NOT NULL,
    KCAL INT,
    PROTEIN INT,
    CARBS INT,
    FATS INT,
    INGREDIENTS VARCHAR(1000),
    PRICE DECIMAL(8,2) NOT NULL,
    CATEGORY_ID INT
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ALLERGY (
    ID INT GENERATED ALWAYS AS IDENTITY,
    TYPE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECIPE_ALLERGY (
    RECIPE_ID INT NOT NULL,
    ALLERGY_ID INT NOT NULL,
    PRIMARY KEY (RECIPE_ID, ALLERGY_ID),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID),
    FOREIGN KEY (ALLERGY_ID) REFERENCES ALLERGY(ID)
);

ALTER TABLE RECIPE ADD CONSTRAINT IF NOT EXISTS FK_RECIPE_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);

    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (1, 'GLUTEN');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (2, 'LACTOSE');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (3, 'NUTS');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (4, 'SEAFOOD');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (5, 'EGGS');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (6, 'SOY');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (7, 'SESAME');
    MERGE INTO ALLERGY (ID, TYPE) KEY(TYPE) VALUES (8, 'MUSTARD');